version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=kev
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
